### ISSUE TITLE
Refactor methods in InGameController

### ISSUE THREAD

**Issue by jimmy-burba** [emwani1/FreeCol#1]
We want to reduce the overall average cyclomatic complexity of the methods in this class.

**Comment by tyoung17** [comment]
Was able to refactor 26 methods within the InGameController class. The overall cyclomatic complexity of the class started at 5.85. After refactoring the overall cyclomatic complexity is now at 4.90. The moveDirection method within the InGameController class has a cyclomatic complexity of 57 due to it being one long switch statement with all possible move types. Due to this method the cyclomatic complexity of the class still remains high.
